const fs = require('fs');
const path = require('path');

const glob = (dir) => fs.readdirSync(dir).reduce((files, file) => {
  const name = path.join(dir, file);
  return fs.statSync(name).isDirectory() ? [...files, ...glob(name)] : [...files, name];
}, []);

const files = glob('src').filter(f => f.endsWith('.jsx') || f.endsWith('.js'));
const allKeys = new Set();
const tamilMap = {};
const hindiMap = {};

// Load existing hindiDictionary
if (fs.existsSync('src/context/hindiDictionary.json')) {
  try {
    const existingHi = JSON.parse(fs.readFileSync('src/context/hindiDictionary.json', 'utf8'));
    Object.assign(hindiMap, existingHi);
  } catch (e) {}
}

// Load extracted_t_calls if exists
if (fs.existsSync('extracted_t_calls.json')) {
  try {
    const extracted = JSON.parse(fs.readFileSync('extracted_t_calls.json', 'utf8'));
    if (extracted.keys) extracted.keys.forEach(k => k && allKeys.add(k));
    if (extracted.tamil) Object.assign(tamilMap, extracted.tamil);
    if (extracted.hindi) Object.assign(hindiMap, extracted.hindi);
  } catch (e) {}
}

// Regex to catch t('en', 'ta', 'hi'...) and variations
const reSingle = /t\(\s*'([^'\\]*(?:\\.[^'\\]*)*)'(?:\s*,\s*'([^'\\]*(?:\\.[^'\\]*)*)')?(?:\s*,\s*'([^'\\]*(?:\\.[^'\\]*)*)')?/g;
const reDouble = /t\(\s*"([^"\\]*(?:\\.[^"\\]*)*)"(?:\s*,\s*"([^"\\]*(?:\\.[^"\\]*)*)")?(?:\s*,\s*"([^"\\]*(?:\\.[^"\\]*)*)")?/g;

files.forEach(f => {
  const content = fs.readFileSync(f, 'utf8');
  let m;
  while ((m = reSingle.exec(content)) !== null) {
    const en = m[1].replace(/\\'/g, "'").trim();
    const ta = m[2] ? m[2].replace(/\\'/g, "'").trim() : '';
    const hi = m[3] ? m[3].replace(/\\'/g, "'").trim() : '';
    if (en && en !== ',' && en !== '') {
      allKeys.add(en);
      if (ta && !tamilMap[en]) tamilMap[en] = ta;
      if (hi && !hindiMap[en]) hindiMap[en] = hi;
    }
  }
  while ((m = reDouble.exec(content)) !== null) {
    const en = m[1].replace(/\\"/g, '"').trim();
    const ta = m[2] ? m[2].replace(/\\"/g, '"').trim() : '';
    const hi = m[3] ? m[3].replace(/\\"/g, '"').trim() : '';
    if (en && en !== ',' && en !== '') {
      allKeys.add(en);
      if (ta && !tamilMap[en]) tamilMap[en] = ta;
      if (hi && !hindiMap[en]) hindiMap[en] = hi;
    }
  }
});

// Explicit domain terms
const extraTerms = [
  'Kangayam', 'Umblachery', 'Murrah Buffalo', 'Bargur', 'Tellicherry Goat', 'Kanni Adu Goat',
  'Merino', 'Dorper', 'Suffolk', 'Rambouillet', 'Boer', 'Jamnapari',
  'Cow', 'Buffalo', 'Goat', 'Sheep',
  'Healthy', 'Warning', 'Emergency', 'Safe', 'Breached', 'Consulting', 'Resolved',
  'Male', 'Female',
  'Daily', 'Weekly', 'Monthly',
  'Collar Telemetry Sim', 'Heart Rate (Collar 101)', 'Body Temp (Collar 101)',
  'Geofence Breach (Collar 101)', 'Simulate Battery Drain', 'Live Map Wander',
  'Active Telemetry Simulation', 'Normal (~38.5°)', 'Fever (>40.5°)',
  'High Heart Rate', 'Low Heart Rate', 'High Temperature (Fever)', 'Low Battery Alert',
  'Health Alert', 'New Collar Registered', 'Digital Prescription Received',
  'Verified System Log', 'Report Date', 'Animal ID', 'Generated By', 'Disclaimer',
  'Dr. Rajesh Kannan, M.V.Sc', 'Dr. Rajesh Kannan', 'Green Valley Farm', 'Geofence Center Node',
  'Select application language.', 'English', 'Tamil', 'Malayalam', 'Hindi', 'Kannada',
  'Herd Analytics', 'Doctor Profile', 'Authorized Government Veterinarian',
  'BioSense Automated Health Assessor', 'BioSense Tele-Call', 'Madurai East Farm'
];

extraTerms.forEach(t => allKeys.add(t));

const result = {
  totalKeys: allKeys.size,
  keys: Array.from(allKeys).sort(),
  tamil: tamilMap,
  hindi: hindiMap
};

fs.writeFileSync('all_translation_keys.json', JSON.stringify(result, null, 2));
console.log('Total keys gathered:', allKeys.size);
console.log('Tamil keys gathered:', Object.keys(tamilMap).length);
console.log('Hindi keys gathered:', Object.keys(hindiMap).length);
